services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:123600@db:3306/fastapi
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: fastapi
      MYSQL_ROOT_PASSWORD: 123600
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
